services:
  - type: web
    name: bajaj-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyDpXLF8vl2Pn3YLxpoEqUuALLwIZSZj0TU # your actual key
